apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: ns-37
data:
  DB_NAME: "mydatabase"
  DB_USER: "myuser"
  DB_HOST: "postgres-service"  # Имя PostgreSQL сервиса внутри кластера
  DB_PORT: "5432"
